database = {"count":1000,"docs":[{"phy":65,                                  #player-ratings-database
                                  "commonnameid":0,
                                  "birthdate":"6/24/1987 12:00:00 AM",
                                  "playerjerseyname":"Messi",
                                  "penalties":75,
                                  "strength":69,
                                  "def":38,
                                  "skillmoves":4,
                                  "stamina":72,
                                  "weakfootabilitytypecode":4,
                                  "longshots":94,
                                  "preferredposition4label":"",
                                  "ballcontrol":96,
                                  "volleys":88,
                                  "gkhandling":11,
                                  "acceleration":91,
                                  "contractvaliduntil":2021,
                                  "pac":85,
                                  "balance":95,
                                  "teamid":241,
                                  "hasphoto":"TRUE",
                                  "shotpower":86,
                                  "dri":95,
                                  "potential":93,
                                  "height":170,
                                  "pas":91,
                                  "weight":72,
                                  "longpassing":91,
                                  "standingtackle":35,
                                  "preferredfoot":2,
                                  "crossing":85,
                                  "freekickaccuracy":94,
                                  "vision":95,
                                  "nationality":52,
                                  "leagueid":53,
                                  "sho":92,
                                  "agility":91,
                                  "status":"published",
                                  "firstname":"Lionel",
                                  "playerjerseynameid":16250,
                                  "gender":0,
                                  "composure":96,
                                  "jumping":68,
                                  "curve":93,
                                  "gkkicking":15,
                                  "slidingtackle":24,
                                  "gkreflexes":8,
                                  "preferredposition1label":"RW",
                                  "finishing":95,
                                  "defensiveworkrate":1,
                                  "commonname":"",
                                  "dribbling":96,
                                  "surname":"Messi",
                                  "preferredposition1":23,
                                  "positioning":93,
                                  "attackingworkrate":0,
                                  "preferredposition3":21,
                                  "iteration":"fifa-21-ratings",
                                  "preferredposition2":25,
                                  "isfakeplayer":"FALSE",
                                  "preferredposition2label":"ST",
                                  "preferredposition4":-1,
                                  "lastnameid":16250,
                                  "gkdiving":6,
                                  "leaguename":"Spain Primera División (1)",
                                  "firstnameid":14290,
                                  "preferredposition3label":"CF",
                                  "aggression":44,
                                  "interceptions":40,
                                  "shortpassing":91,
                                  "gkpositioning":14,
                                  "marking":32,
                                  "sprintspeed":80,
                                  "headingaccuracy":70,
                                  "fullNameForSearch":"Lionel Messi",
                                  "reactions":94,
                                  "ranking":1,
                                  "overall_rating":93,
                                  "teamname":"FC Barcelona",
                                  "primaryKey":158023}]}
                                 
def get_player(name):
    global database
    for I in database['docs']:
        if I['playerjerseyname'].lower()==name.lower():
            if I['ranking']>100:
                return f"{ I['playerjerseyname']} : {I['overall_rating']}"
            return I['primaryKey']
